Rails.application.routes.draw do
  root 'patients#list'

  get 'patients/list'
  get 'patients/new'
  post 'patients/create'
  patch 'patients/update'
  get 'patients/list'
  get 'patients/show'
  get 'patients/edit'
  get 'patients/delete'
  get 'patients/update'

  get 'doctors/list'
  get 'doctors/new'
  post 'doctors/create'
  patch 'doctors/update'
  get 'doctors/list'
  get 'doctors/show'
  get 'doctors/edit'
  get 'doctors/delete'
  get 'doctors/update'

  get 'medicines/list'
  get 'medicines/new'
  post 'medicines/create'
  patch 'medicines/update'
  get 'medicines/list'
  get 'medicines/show'
  get 'medicines/edit'
  get 'medicines/delete'
  get 'medicines/update'

  get 'appointments/list'
  get 'appointments/new'
  post 'appointments/create'
  patch 'appointments/update'
  get 'appointments/list'
  get 'appointments/show'
  get 'appointments/edit'
  get 'appointments/delete'
  get 'appointments/update'
  get 'appointments/show_patients'
  get 'appointments/show_medicines'
end
